"""create reports and report_images tables

Revision ID: e0ba413fe3f6
Revises: d924f659f3ad
Create Date: 2026-09-25 08:15:59.439936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ba413fe3f6'
down_revision: Union[str, Sequence[str], None] = 'd924f659f3ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('lost', 'found', name='report_kind', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('document_type', sa.Enum('cni', 'permis', 'passeport', 'carte_etudiant', 'carte_consulaire', 'autre', name='document_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('document_number_hmac', sa.String(length=64), nullable=True),
    sa.Column('owner_name_masked', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('commune', sa.String(length=80), nullable=True),
    sa.Column('place_detail', sa.String(length=255), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'matched', 'closed', name='report_status', native_enum=False, create_constraint=True, length=30), server_default='open', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('document_number_hmac IS NULL OR char_length(document_number_hmac) = 64', name=op.f('ck_reports_hmac_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('ix_reports_matching', 'reports', ['kind', 'document_number_hmac'], unique=False, postgresql_where=sa.text('document_number_hmac IS NOT NULL'))
    op.create_index('ix_reports_public_list', 'reports', ['is_published', 'status', 'document_type'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('report_images',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_images_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_images')),
    sa.UniqueConstraint('storage_path', name=op.f('uq_report_images_storage_path'))
    )
    op.create_index(op.f('ix_report_images_report_id'), 'report_images', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_images_report_id'), table_name='report_images')
    op.drop_table('report_images')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index('ix_reports_public_list', table_name='reports')
    op.drop_index('ix_reports_matching', table_name='reports', postgresql_where=sa.text('document_number_hmac IS NOT NULL'))
    op.drop_table('reports')
    # ### end Alembic commands ###
