"""add claims, gps and verification question

Revision ID: 990156f7bf24
Revises: e0ba413fe3f6
Create Date: 2026-09-27 20:07:10.133515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990156f7bf24'
down_revision: Union[str, Sequence[str], None] = 'e0ba413fe3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('claimant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', 'withdrawn', name='claim_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('answer_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], name=op.f('fk_claims_claimant_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_claims_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('report_id', 'claimant_id', name='one_claim_per_person')
    )
    op.create_index(op.f('ix_claims_claimant_id'), 'claims', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_claims_report_id'), 'claims', ['report_id'], unique=False)
    op.add_column('reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('verification_question', sa.String(length=200), nullable=True))
    op.add_column('reports', sa.Column('verification_answer_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'verification_answer_hash')
    op.drop_column('reports', 'verification_question')
    op.drop_column('reports', 'longitude')
    op.drop_column('reports', 'latitude')
    op.drop_index(op.f('ix_claims_report_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claimant_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
